import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import Link from "next/link";

import "@/styles/globals.css";
import LogOut from "./logout";
import { buttonVariants } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={`bg-black text-white ${inter.className}`}>
        <nav className="flex justify-end m-4">
          {!!session && <LogOut />}
          {!session && (
            <Link
              href="/sign-in"
              className={buttonVariants({ variant: "default" })}
            >
              Sign-In
            </Link>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
